### ISSUE TITLE
Mac平台 map地图材质异常，显示红色

### ISSUE THREAD

**Issue by zilongshanren** [zzjfengqing/ET-EUI#7]
另外，也无法创建出骷髅人：

```
/Users/lionqu/Github/ET-EUI/Bin/Server
2022-03-17 22:00:10.9937 not found actor: Process  10010 448758180454072328 { "_t" : "M2C_CreateUnits", "Units" : [{ "Ks" : [1000, 1003], "Vs" : [60000, 15000], "UnitId" : 1197244622208827397, "ConfigId" : 1001, "Type" : 1, "X" : -10.0, "Y" : 0.0, "Z" : -10.0, "ForwardX" : 0.0, "ForwardY" : 0.0, "ForwardZ" : 1.0, "MoveInfo" : null }] }
   at ET.SessionStreamDispatcherServerInner.Dispatch(Session session, MemoryStream memoryStream) in /Users/lionqu/Github/ET-EUI/Server/Hotfix/Demo/Session/SessionStreamDispatcherServerInner.cs:line 33
   at ET.SessionStreamDispatcherSystem.Dispatch(SessionStreamDispatcher self, Int32 type, Session session, MemoryStream memoryStream) in /Users/lionqu/Github/ET-EUI/Unity/Codes/Hotfix/Module/Message/SessionStreamDispatcherSystem.cs:line 81
   at ET.NetInnerComponentSystem.OnRead(NetInnerComponent self, Int64 channelId, MemoryStream memoryStream) in /Users/lionqu/Github/ET-EUI/Server/Hotfix/Module/MessageInner/NetInnerComponentSystem.cs:line 63
   at ET.AService.OnRead(Int64 channelId, MemoryStream memoryStream) in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Module/Network/AService.cs:line 53
   at ET.TChannel.OnRead(MemoryStream memoryStream) in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Module/NetworkTCP/TChannel.cs:line 392
   at ET.TChannel.HandleRecv(Object o) in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Module/NetworkTCP/TChannel.cs:line 280
   at ET.TChannel.OnRecvComplete(Object o) in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Module/NetworkTCP/TChannel.cs:line 228
   at ET.TChannel.<>c__DisplayClass10_0.<OnComplete>b__1() in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Module/NetworkTCP/TChannel.cs:line 37
   at ET.ThreadSynchronizationContext.Update() in /Users/lionqu/Github/ET-EUI/Unity/Assets/Mono/Core/ThreadSynchronizationContext.cs:line 34
   at ET.Game.Update() in /Users/lionqu/Github/ET-EUI/Unity/Codes/Model/Core/Entity/Game.cs:line 38
   at ET.Program.Main(String[] args) in /Users/lionqu/Github/ET-EUI/Server/App/Program.cs:line 50

      


```

**Comment by zilongshanren** [comment]
使用官方的ET最新分支是正常的。修复mat shader为 mobile/vertex lit 暂时解决
